# Generated by Django 2.0.1 on 2018-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0002_auto_20180130_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='boincproject',
            name='icon',
            field=models.CharField(default='none.png', max_length=50, verbose_name='Icon'),
        ),
    ]
