# Generated by Django 2.0.1 on 2018-02-07 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0008_logitem_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
