# Generated by Django 2.0.1 on 2018-01-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boincproject',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='boincproject',
            name='full_name',
            field=models.CharField(default='none', max_length=100, verbose_name='Long name'),
        ),
        migrations.AddField(
            model_name='boincproject',
            name='url',
            field=models.CharField(default='none', max_length=500, verbose_name='URL'),
        ),
    ]
