# Generated by Django 2.0.1 on 2018-02-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0004_boincsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='boincsettings',
            name='logdir',
            field=models.CharField(default='/home/isilanes/.LOGs/boinc', max_length=200, verbose_name='Log dir'),
        ),
    ]
