# Generated by Django 2.0.1 on 2018-02-01 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0005_boincsettings_logdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='boincsettings',
            name='ref_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Reference date'),
        ),
    ]
