# Generated by Django 2.0.1 on 2018-02-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0007_logitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bhs.BOINCProject'),
        ),
    ]
