# Generated by Django 2.0.1 on 2018-02-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0009_auto_20180207_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogItem',
            new_name='LogEntry',
        ),
    ]
