# Generated by Django 2.0.1 on 2018-02-09 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0010_auto_20180209_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boincsettings',
            name='ref_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Reference date'),
        ),
    ]
